/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalDpaRouteImport } from './routes/legal.dpa'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as DriverTripsRouteImport } from './routes/driver.trips'
import { Route as DriverProfileRouteImport } from './routes/driver.profile'
import { Route as DriverDocumentsRouteImport } from './routes/driver.documents'
import { Route as ApiBlakeRouteImport } from './routes/api/blake'
import { Route as AdminVehiclesRouteImport } from './routes/admin.vehicles'
import { Route as AdminTripsRouteImport } from './routes/admin.trips'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminRecoverRouteImport } from './routes/admin.recover'
import { Route as AdminPoliciesRouteImport } from './routes/admin.policies'
import { Route as AdminOperationsRouteImport } from './routes/admin.operations'
import { Route as AdminMfaRouteImport } from './routes/admin.mfa'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminHealthRouteImport } from './routes/admin.health'
import { Route as AdminDriversRouteImport } from './routes/admin.drivers'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as DriverTripsIdRouteImport } from './routes/driver.trips.$id'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as AdminVehiclesIdRouteImport } from './routes/admin.vehicles.$id'
import { Route as AdminTripsIdRouteImport } from './routes/admin.trips.$id'
import { Route as AdminDriversIdRouteImport } from './routes/admin.drivers.$id'
import { Route as AdminCustomersIdRouteImport } from './routes/admin.customers.$id'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriverRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDpaRoute = LegalDpaRouteImport.update({
  id: '/legal/dpa',
  path: '/legal/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverTripsRoute = DriverTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => DriverRoute,
} as any)
const DriverProfileRoute = DriverProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DriverRoute,
} as any)
const DriverDocumentsRoute = DriverDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DriverRoute,
} as any)
const ApiBlakeRoute = ApiBlakeRouteImport.update({
  id: '/api/blake',
  path: '/api/blake',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVehiclesRoute = AdminVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTripsRoute = AdminTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecoverRoute = AdminRecoverRouteImport.update({
  id: '/recover',
  path: '/recover',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPoliciesRoute = AdminPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOperationsRoute = AdminOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMfaRoute = AdminMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const DriverTripsIdRoute = DriverTripsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DriverTripsRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVehiclesIdRoute = AdminVehiclesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminVehiclesRoute,
} as any)
const AdminTripsIdRoute = AdminTripsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminTripsRoute,
} as any)
const AdminDriversIdRoute = AdminDriversIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminDriversRoute,
} as any)
const AdminCustomersIdRoute = AdminCustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/driver': typeof DriverRouteWithChildren
  '/history': typeof HistoryRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/drivers': typeof AdminDriversRouteWithChildren
  '/admin/health': typeof AdminHealthRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mfa': typeof AdminMfaRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/recover': typeof AdminRecoverRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trips': typeof AdminTripsRouteWithChildren
  '/admin/vehicles': typeof AdminVehiclesRouteWithChildren
  '/api/blake': typeof ApiBlakeRoute
  '/driver/documents': typeof DriverDocumentsRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/trips': typeof DriverTripsRouteWithChildren
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/dpa': typeof LegalDpaRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/r/$code': typeof RCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/drivers/$id': typeof AdminDriversIdRoute
  '/admin/trips/$id': typeof AdminTripsIdRoute
  '/admin/vehicles/$id': typeof AdminVehiclesIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/driver/trips/$id': typeof DriverTripsIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/history': typeof HistoryRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/drivers': typeof AdminDriversRouteWithChildren
  '/admin/health': typeof AdminHealthRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mfa': typeof AdminMfaRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/recover': typeof AdminRecoverRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trips': typeof AdminTripsRouteWithChildren
  '/admin/vehicles': typeof AdminVehiclesRouteWithChildren
  '/api/blake': typeof ApiBlakeRoute
  '/driver/documents': typeof DriverDocumentsRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/trips': typeof DriverTripsRouteWithChildren
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/dpa': typeof LegalDpaRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/r/$code': typeof RCodeRoute
  '/admin': typeof AdminIndexRoute
  '/driver': typeof DriverIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/drivers/$id': typeof AdminDriversIdRoute
  '/admin/trips/$id': typeof AdminTripsIdRoute
  '/admin/vehicles/$id': typeof AdminVehiclesIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/driver/trips/$id': typeof DriverTripsIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/driver': typeof DriverRouteWithChildren
  '/history': typeof HistoryRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/drivers': typeof AdminDriversRouteWithChildren
  '/admin/health': typeof AdminHealthRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mfa': typeof AdminMfaRoute
  '/admin/operations': typeof AdminOperationsRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/recover': typeof AdminRecoverRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trips': typeof AdminTripsRouteWithChildren
  '/admin/vehicles': typeof AdminVehiclesRouteWithChildren
  '/api/blake': typeof ApiBlakeRoute
  '/driver/documents': typeof DriverDocumentsRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/trips': typeof DriverTripsRouteWithChildren
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/dpa': typeof LegalDpaRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/r/$code': typeof RCodeRoute
  '/admin/': typeof AdminIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/drivers/$id': typeof AdminDriversIdRoute
  '/admin/trips/$id': typeof AdminTripsIdRoute
  '/admin/vehicles/$id': typeof AdminVehiclesIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/driver/trips/$id': typeof DriverTripsIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/book'
    | '/driver'
    | '/history'
    | '/reset-password'
    | '/admin/customers'
    | '/admin/drivers'
    | '/admin/health'
    | '/admin/login'
    | '/admin/mfa'
    | '/admin/operations'
    | '/admin/policies'
    | '/admin/recover'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/trips'
    | '/admin/vehicles'
    | '/api/blake'
    | '/driver/documents'
    | '/driver/profile'
    | '/driver/trips'
    | '/legal/cookies'
    | '/legal/dpa'
    | '/legal/privacy'
    | '/legal/terms'
    | '/r/$code'
    | '/admin/'
    | '/driver/'
    | '/admin/customers/$id'
    | '/admin/drivers/$id'
    | '/admin/trips/$id'
    | '/admin/vehicles/$id'
    | '/api/public/health'
    | '/driver/trips/$id'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/book'
    | '/history'
    | '/reset-password'
    | '/admin/customers'
    | '/admin/drivers'
    | '/admin/health'
    | '/admin/login'
    | '/admin/mfa'
    | '/admin/operations'
    | '/admin/policies'
    | '/admin/recover'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/trips'
    | '/admin/vehicles'
    | '/api/blake'
    | '/driver/documents'
    | '/driver/profile'
    | '/driver/trips'
    | '/legal/cookies'
    | '/legal/dpa'
    | '/legal/privacy'
    | '/legal/terms'
    | '/r/$code'
    | '/admin'
    | '/driver'
    | '/admin/customers/$id'
    | '/admin/drivers/$id'
    | '/admin/trips/$id'
    | '/admin/vehicles/$id'
    | '/api/public/health'
    | '/driver/trips/$id'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/book'
    | '/driver'
    | '/history'
    | '/reset-password'
    | '/admin/customers'
    | '/admin/drivers'
    | '/admin/health'
    | '/admin/login'
    | '/admin/mfa'
    | '/admin/operations'
    | '/admin/policies'
    | '/admin/recover'
    | '/admin/security'
    | '/admin/settings'
    | '/admin/trips'
    | '/admin/vehicles'
    | '/api/blake'
    | '/driver/documents'
    | '/driver/profile'
    | '/driver/trips'
    | '/legal/cookies'
    | '/legal/dpa'
    | '/legal/privacy'
    | '/legal/terms'
    | '/r/$code'
    | '/admin/'
    | '/driver/'
    | '/admin/customers/$id'
    | '/admin/drivers/$id'
    | '/admin/trips/$id'
    | '/admin/vehicles/$id'
    | '/api/public/health'
    | '/driver/trips/$id'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  DriverRoute: typeof DriverRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiBlakeRoute: typeof ApiBlakeRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalDpaRoute: typeof LegalDpaRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  RCodeRoute: typeof RCodeRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/': {
      id: '/driver/'
      path: '/'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof DriverRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/dpa': {
      id: '/legal/dpa'
      path: '/legal/dpa'
      fullPath: '/legal/dpa'
      preLoaderRoute: typeof LegalDpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/trips': {
      id: '/driver/trips'
      path: '/trips'
      fullPath: '/driver/trips'
      preLoaderRoute: typeof DriverTripsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/profile': {
      id: '/driver/profile'
      path: '/profile'
      fullPath: '/driver/profile'
      preLoaderRoute: typeof DriverProfileRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/documents': {
      id: '/driver/documents'
      path: '/documents'
      fullPath: '/driver/documents'
      preLoaderRoute: typeof DriverDocumentsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/api/blake': {
      id: '/api/blake'
      path: '/api/blake'
      fullPath: '/api/blake'
      preLoaderRoute: typeof ApiBlakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vehicles': {
      id: '/admin/vehicles'
      path: '/vehicles'
      fullPath: '/admin/vehicles'
      preLoaderRoute: typeof AdminVehiclesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trips': {
      id: '/admin/trips'
      path: '/trips'
      fullPath: '/admin/trips'
      preLoaderRoute: typeof AdminTripsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recover': {
      id: '/admin/recover'
      path: '/recover'
      fullPath: '/admin/recover'
      preLoaderRoute: typeof AdminRecoverRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/policies': {
      id: '/admin/policies'
      path: '/policies'
      fullPath: '/admin/policies'
      preLoaderRoute: typeof AdminPoliciesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/operations': {
      id: '/admin/operations'
      path: '/operations'
      fullPath: '/admin/operations'
      preLoaderRoute: typeof AdminOperationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mfa': {
      id: '/admin/mfa'
      path: '/mfa'
      fullPath: '/admin/mfa'
      preLoaderRoute: typeof AdminMfaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/driver/trips/$id': {
      id: '/driver/trips/$id'
      path: '/$id'
      fullPath: '/driver/trips/$id'
      preLoaderRoute: typeof DriverTripsIdRouteImport
      parentRoute: typeof DriverTripsRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vehicles/$id': {
      id: '/admin/vehicles/$id'
      path: '/$id'
      fullPath: '/admin/vehicles/$id'
      preLoaderRoute: typeof AdminVehiclesIdRouteImport
      parentRoute: typeof AdminVehiclesRoute
    }
    '/admin/trips/$id': {
      id: '/admin/trips/$id'
      path: '/$id'
      fullPath: '/admin/trips/$id'
      preLoaderRoute: typeof AdminTripsIdRouteImport
      parentRoute: typeof AdminTripsRoute
    }
    '/admin/drivers/$id': {
      id: '/admin/drivers/$id'
      path: '/$id'
      fullPath: '/admin/drivers/$id'
      preLoaderRoute: typeof AdminDriversIdRouteImport
      parentRoute: typeof AdminDriversRoute
    }
    '/admin/customers/$id': {
      id: '/admin/customers/$id'
      path: '/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AdminCustomersIdRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminCustomersRouteChildren {
  AdminCustomersIdRoute: typeof AdminCustomersIdRoute
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersIdRoute: AdminCustomersIdRoute,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(
  AdminCustomersRouteChildren,
)

interface AdminDriversRouteChildren {
  AdminDriversIdRoute: typeof AdminDriversIdRoute
}

const AdminDriversRouteChildren: AdminDriversRouteChildren = {
  AdminDriversIdRoute: AdminDriversIdRoute,
}

const AdminDriversRouteWithChildren = AdminDriversRoute._addFileChildren(
  AdminDriversRouteChildren,
)

interface AdminTripsRouteChildren {
  AdminTripsIdRoute: typeof AdminTripsIdRoute
}

const AdminTripsRouteChildren: AdminTripsRouteChildren = {
  AdminTripsIdRoute: AdminTripsIdRoute,
}

const AdminTripsRouteWithChildren = AdminTripsRoute._addFileChildren(
  AdminTripsRouteChildren,
)

interface AdminVehiclesRouteChildren {
  AdminVehiclesIdRoute: typeof AdminVehiclesIdRoute
}

const AdminVehiclesRouteChildren: AdminVehiclesRouteChildren = {
  AdminVehiclesIdRoute: AdminVehiclesIdRoute,
}

const AdminVehiclesRouteWithChildren = AdminVehiclesRoute._addFileChildren(
  AdminVehiclesRouteChildren,
)

interface AdminRouteChildren {
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  AdminDriversRoute: typeof AdminDriversRouteWithChildren
  AdminHealthRoute: typeof AdminHealthRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMfaRoute: typeof AdminMfaRoute
  AdminOperationsRoute: typeof AdminOperationsRoute
  AdminPoliciesRoute: typeof AdminPoliciesRoute
  AdminRecoverRoute: typeof AdminRecoverRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTripsRoute: typeof AdminTripsRouteWithChildren
  AdminVehiclesRoute: typeof AdminVehiclesRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  AdminDriversRoute: AdminDriversRouteWithChildren,
  AdminHealthRoute: AdminHealthRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMfaRoute: AdminMfaRoute,
  AdminOperationsRoute: AdminOperationsRoute,
  AdminPoliciesRoute: AdminPoliciesRoute,
  AdminRecoverRoute: AdminRecoverRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTripsRoute: AdminTripsRouteWithChildren,
  AdminVehiclesRoute: AdminVehiclesRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DriverTripsRouteChildren {
  DriverTripsIdRoute: typeof DriverTripsIdRoute
}

const DriverTripsRouteChildren: DriverTripsRouteChildren = {
  DriverTripsIdRoute: DriverTripsIdRoute,
}

const DriverTripsRouteWithChildren = DriverTripsRoute._addFileChildren(
  DriverTripsRouteChildren,
)

interface DriverRouteChildren {
  DriverDocumentsRoute: typeof DriverDocumentsRoute
  DriverProfileRoute: typeof DriverProfileRoute
  DriverTripsRoute: typeof DriverTripsRouteWithChildren
  DriverIndexRoute: typeof DriverIndexRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverDocumentsRoute: DriverDocumentsRoute,
  DriverProfileRoute: DriverProfileRoute,
  DriverTripsRoute: DriverTripsRouteWithChildren,
  DriverIndexRoute: DriverIndexRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  DriverRoute: DriverRouteWithChildren,
  HistoryRoute: HistoryRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiBlakeRoute: ApiBlakeRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalDpaRoute: LegalDpaRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  RCodeRoute: RCodeRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
